eval "$(rbenv init -)"
parse_git_branch() {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/-[\1]/'
}
export PS1="\W\[\e[36m\]\$(parse_git_branch) \[\e[m\]\[\e[31m\]\\$\[\e[m\] "
alias vim='mvim -v' 

if [ -f ~/.git-completion.bash ]; then
  . ~/.git-completion.bash
fi
